### PR TITLE
Add Python 3.13 to CI matrix

### PR DESCRIPTION
**Pull request by dan-blanchard**
Accidentally closed the other one.

### CODE REVIEW

**Comment by dan-blanchard** [comment]
It looks like 3.13 tests fail on Windows, but work on everything else

**Comment by milesgranger** [comment]
Seems like something related to numpy? I don't have immediate availability to dig much into this for now, maybe in a few weeks.

**Comment by dan-blanchard** [comment]
I changed the test requirements to use numpy 2.0+ on python 3.10+ and that straightened things out

**Review by milesgranger — APPROVED** [review]

**Comment by milesgranger** [comment]
Thank you. :+1:

**Pull request merged**
